export default [
  {
    id: 1,
    postedOn: "2023-10-28",
    title: "Android Developer",
    type: "Part Time",
    location: "Remote",
    experience: "Senior Level",
    company: "Facebook",
    skills: ["Kotlin", "MVVM"],
    job_link: "https://Facebook.com/careers",
  },
  {
    id: 2,
    postedOn: "2023-10-02",
    title: "Fronted Developer",
    type: "Part Time",
    location: "Remote",
    experience: "Senior Level",
    company: "Facebook",
    skills: ["React", "Tailwindcss", "NodeJs"],
    job_link: "https://Facebook.com/careers",
  },
  {
    id: 3,
    postedOn: "2023-11-02",
    title: "Backend Developer",
    type: "Full Time",
    location: "Remote",
    experience: "Senior Level",
    company: "Oracle",
    skills: ["Java", "NodeJS", "ExpressJS"],
    job_link: "https://oracle.com/careers",
  },
  {
    id: 4,
    postedOn: "2023-11-02",
    title: "Backend Developer",
    type: "Full Time",
    location: "Remote",
    experience: "Senior Level",
    company: "Oracle",
    skills: ["Java", "NodeJS", "ExpressJS"],
    job_link: "https://oracle.com/careers",
  },
];
